In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
import warnings

warnings.filterwarnings("ignore")

data_dir = "/Users/loganheydt/Desktop/Data/GitHub/Kaggle_competitions/March_Machine_Learning_Mania_2026/data"

In [3]:
M_regular_results = pd.read_csv(f"{data_dir}/MRegularSeasonDetailedResults.csv")
M_tourney_results = pd.read_csv(f"{data_dir}/MNCAATourneyDetailedResults.csv")
M_seeds = pd.read_csv(f"{data_dir}/MNCAATourneySeeds.csv")

W_regular_results = pd.read_csv(f"{data_dir}/WRegularSeasonDetailedResults.csv")
W_tourney_results = pd.read_csv(f"{data_dir}/WNCAATourneyDetailedResults.csv")
W_seeds = pd.read_csv(f"{data_dir}/WNCAATourneySeeds.csv")

In [4]:
# using the last 20 years of data, change it needed
cut_off = 2005

regular_results = M_regular_results.loc[M_regular_results['Season'] >= cut_off]
tourney_results = M_tourney_results.loc[M_tourney_results['Season'] >= cut_off]
seeds = M_seeds.loc[M_seeds['Season'] >= cut_off]

In [5]:
regular_results.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
9187,2005,10,1128,79,1105,69,N,0,25,50,...,22,18,27,12,21,8,8,5,1,25
9188,2005,10,1143,78,1415,61,H,0,25,55,...,15,12,20,18,26,14,16,3,1,27
9189,2005,10,1206,69,1236,51,N,0,28,58,...,17,7,10,13,23,11,16,3,1,7
9190,2005,10,1272,102,1366,40,H,0,37,77,...,13,5,9,14,22,6,22,5,5,21
9191,2005,10,1280,53,1193,49,N,0,19,45,...,17,16,19,13,23,8,11,10,3,22

In [6]:
tourney_results.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
128,2005,134,1324,79,1105,69,N,0,29,57,...,28,13,18,10,19,16,14,6,3,17
129,2005,136,1112,66,1429,53,N,0,23,49,...,19,6,10,12,20,15,12,6,3,16
130,2005,136,1130,85,1335,65,N,0,30,52,...,30,5,10,16,18,17,17,11,2,19
131,2005,136,1153,76,1234,64,N,0,27,57,...,17,19,25,16,27,5,11,6,1,20
132,2005,136,1211,74,1457,64,N,0,27,59,...,26,10,12,10,26,16,13,4,0,19

In [7]:
seeds.head()

      Season Seed  TeamID
1284    2005  W01    1449
1285    2005  W02    1448
1286    2005  W03    1211
1287    2005  W04    1257
1288    2005  W05    1210